test shell wrappers:
  stage: test
  image: docker:19.03.1
  services:
    - docker:dind
  parallel:
    matrix:
    - COMMAND:
      - "bin/curl --help"
      - "bin/gradle -version"
      - "bin/hugo version"
      - "bin/mvn -version"
      - "bin/npm -version"
  variables:
    DOCKER_OPTS: "--interactive"
  script: $COMMAND
