test:
  stage: test
  image: docker:19.03.1
  services:
    - docker:dind
  parallel:
    matrix:
    - COMMAND:
      - echo "hello world"
      - "bin/gradle init"
      - "bin/npm -version"
  variables:
    DOCKER_OPTS: "--interactive"
  script: $COMMAND
